from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path
import subprocess
from unittest.mock import patch


LIB_DIR = Path(__file__).resolve().parents[1] / "raspi_pxe_docker_fleet" / "rootfs" / "usr" / "local" / "lib" / "ha-pxe"
if str(LIB_DIR) not in sys.path:
    sys.path.insert(0, str(LIB_DIR))

from ha_pxe.client.firstboot import (
    _configure_services,
    _start_command_listener,
    ensure_kernel_dhcp_resolver,
    ensure_networkmanager_ready,
    repair_kernel_dhcp_resolver_if_needed,
    wait_for_time_sync,
)


class _FakeLogger:
    def __init__(self) -> None:
        self.messages: list[str] = []

    def info(self, message: str) -> None:
        self.messages.append(f"info:{message}")

    def warning(self, message: str) -> None:
        self.messages.append(f"warn:{message}")


class EnsureKernelDhcpResolverTests(unittest.TestCase):
    def test_uses_initramfs_dhcp_when_kernel_dhcp_data_is_absent(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "etc").mkdir()
            fallback = root / "run/ha-pxe-initramfs/resolv.conf"
            fallback.parent.mkdir(parents=True)
            fallback.write_text("search home.example\nnameserver 192.0.2.1\n")
            ensure_kernel_dhcp_resolver(_FakeLogger(), root=root)
            self.assertIn("nameserver 192.0.2.1", (root / "etc/resolv.conf").read_text())
            self.assertIn("search home.example", (root / "etc/resolv.conf").read_text())

    def test_ensure_kernel_dhcp_resolver_writes_resolv_conf_from_proc_net_pnp(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver 8.8.8.8\n", encoding="utf-8")

            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text(
                "#PROTO: DHCP\n"
                "domain home.nyanya.org\n"
                "nameserver 192.168.25.1\n"
                "nameserver 1.1.1.1\n",
                encoding="utf-8",
            )

            target = ensure_kernel_dhcp_resolver(logger, root=root_dir)

            self.assertEqual(target, "/etc/resolv.conf")
            self.assertFalse(resolv_path.is_symlink())
            self.assertEqual(
                resolv_path.read_text(encoding="utf-8"),
                "# Generated by HA-PXE from kernel DHCP boot data\n"
                "search home.nyanya.org\n"
                "nameserver 192.168.25.1\n"
                "nameserver 1.1.1.1\n",
            )

    def test_ensure_kernel_dhcp_resolver_raises_when_nameserver_is_missing(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver 8.8.8.8\n", encoding="utf-8")
            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text("domain home.nyanya.org\n", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "did not provide any nameserver entries"):
                ensure_kernel_dhcp_resolver(logger, root=root_dir)

            self.assertFalse(resolv_path.is_symlink())
            self.assertEqual(resolv_path.read_text(encoding="utf-8"), "nameserver 8.8.8.8\n")

    def test_repair_kernel_dhcp_resolver_refreshes_empty_resolv_conf(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("# Managed by HA-PXE; populated from /proc/net/pnp on first boot\n", encoding="utf-8")

            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text(
                "#PROTO: DHCP\n"
                "domain home.nyanya.org\n"
                "nameserver 192.168.25.1\n",
                encoding="utf-8",
            )

            repaired = repair_kernel_dhcp_resolver_if_needed(logger, root=root_dir)

            self.assertTrue(repaired)
            self.assertIn(
                "warn:/etc/resolv.conf does not contain any nameserver entries; refreshing it from kernel DHCP boot data",
                logger.messages,
            )
            self.assertEqual(
                resolv_path.read_text(encoding="utf-8"),
                "# Generated by HA-PXE from kernel DHCP boot data\n"
                "search home.nyanya.org\n"
                "nameserver 192.168.25.1\n",
            )

    def test_repair_kernel_dhcp_resolver_refreshes_loopback_only_resolver(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver ::1\n", encoding="utf-8")

            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text(
                "#PROTO: DHCP\n"
                "nameserver 192.168.25.1\n",
                encoding="utf-8",
            )

            repaired = repair_kernel_dhcp_resolver_if_needed(logger, root=root_dir)

            self.assertTrue(repaired)
            self.assertIn(
                "warn:/etc/resolv.conf only contains loopback nameserver entries; refreshing it from kernel DHCP boot data",
                logger.messages,
            )
            self.assertEqual(
                resolv_path.read_text(encoding="utf-8"),
                "# Generated by HA-PXE from kernel DHCP boot data\n"
                "nameserver 192.168.25.1\n",
            )

    def test_repair_kernel_dhcp_resolver_leaves_working_nameserver_unchanged(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver 192.168.25.1\n", encoding="utf-8")

            repaired = repair_kernel_dhcp_resolver_if_needed(logger, root=root_dir)

            self.assertFalse(repaired)
            self.assertEqual(resolv_path.read_text(encoding="utf-8"), "nameserver 192.168.25.1\n")


class EnsureNetworkManagerReadyTests(unittest.TestCase):
    def test_ensure_networkmanager_ready_checks_service_state_then_resolver(self) -> None:
        logger = _FakeLogger()
        commands: list[list[str]] = []

        def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            commands.append(command)
            check = kwargs.get("check", True)
            del check
            return subprocess.CompletedProcess(command, 0, "", "")

        with (
            patch("ha_pxe.client.firstboot.run", side_effect=fake_run),
        ):
            result = ensure_networkmanager_ready(logger)

        self.assertEqual(
            commands,
            [
                ["systemctl", "is-active", "--quiet", "NetworkManager.service"],
            ],
        )
        self.assertIsNone(result)


class WaitForTimeSyncTests(unittest.TestCase):
    def test_wait_for_time_sync_restarts_timesyncd_and_waits_for_ntp(self) -> None:
        logger = _FakeLogger()
        commands: list[list[str]] = []

        responses = iter(
            [
                subprocess.CompletedProcess(["systemctl", "restart", "systemd-timesyncd.service"], 0, "", ""),
                subprocess.CompletedProcess(["timedatectl", "show", "-p", "NTPSynchronized", "--value"], 0, "no\n", ""),
                subprocess.CompletedProcess(["timedatectl", "show", "-p", "NTPSynchronized", "--value"], 0, "yes\n", ""),
            ]
        )

        def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            commands.append(command)
            del kwargs
            return next(responses)

        with (
            patch("ha_pxe.client.firstboot.run", side_effect=fake_run),
            patch("ha_pxe.client.firstboot.time.sleep"),
        ):
            wait_for_time_sync(logger, attempts=2, delay_seconds=0)

        self.assertEqual(
            commands,
            [
                ["systemctl", "restart", "systemd-timesyncd.service"],
                ["timedatectl", "show", "-p", "NTPSynchronized", "--value"],
                ["timedatectl", "show", "-p", "NTPSynchronized", "--value"],
            ],
        )

    def test_wait_for_time_sync_raises_when_clock_never_synchronizes(self) -> None:
        logger = _FakeLogger()

        def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            del kwargs
            if command[:2] == ["systemctl", "restart"]:
                return subprocess.CompletedProcess(command, 0, "", "")
            return subprocess.CompletedProcess(command, 0, "no\n", "")

        with (
            patch("ha_pxe.client.firstboot.run", side_effect=fake_run),
            patch("ha_pxe.client.firstboot.time.sleep"),
        ):
            with self.assertRaisesRegex(RuntimeError, "did not synchronize before apt operations"):
                wait_for_time_sync(logger, attempts=2, delay_seconds=0)


class ConfigureServicesTests(unittest.TestCase):
    def test_configure_services_enables_command_listener_but_starts_initial_container_sync_first(self) -> None:
        logger = _FakeLogger()
        commands: list[list[str]] = []

        def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            commands.append(command)
            del kwargs
            return subprocess.CompletedProcess(command, 0, "", "")

        with patch("ha_pxe.client.firstboot.run", side_effect=fake_run):
            _configure_services(logger)

        self.assertIn(["systemctl", "enable", "ha-pxe-command-listener.service"], commands)
        self.assertIn("info:Enabled ha-pxe-command-listener.service", logger.messages)
        self.assertNotIn(["systemctl", "start", "ha-pxe-command-listener.service"], commands)
        self.assertIn(["systemctl", "start", "ha-pxe-container-sync.service"], commands)

    def test_start_command_listener_starts_remote_command_service(self) -> None:
        logger = _FakeLogger()

        with patch(
            "ha_pxe.client.firstboot.run",
            return_value=subprocess.CompletedProcess(["systemctl", "start", "ha-pxe-command-listener.service"], 0, "", ""),
        ) as run_mock:
            _start_command_listener(logger)

        run_mock.assert_called_once_with(["systemctl", "start", "ha-pxe-command-listener.service"], check=False)
        self.assertIn("info:Started ha-pxe-command-listener.service", logger.messages)
