"""Resolver helpers for PXE-booted clients."""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass
from pathlib import Path


KERNEL_DHCP_PNP_PATH = "/proc/net/pnp"


@dataclass(frozen=True)
class ResolverConfig:
    nameservers: list[str]
    search_domains: list[str]


def read_resolv_search_domains(path: Path | None = None) -> list[str]:
    resolv_path = path or Path("/etc/resolv.conf")
    try:
        lines = resolv_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []

    for raw_line in lines:
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        if parts[0] == "search":
            return [_normalize_domain(entry) for entry in parts[1:] if _normalize_domain(entry)]
        if parts[0] == "domain":
            domain = _normalize_domain(parts[1])
            return [domain] if domain else []
    return []


def read_resolv_nameservers(path: Path | None = None) -> list[str]:
    resolv_path = path or Path("/etc/resolv.conf")
    try:
        lines = resolv_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []

    nameservers: list[str] = []
    for raw_line in lines:
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2 or parts[0] != "nameserver":
            continue
        nameserver = parts[1].strip()
        if nameserver and nameserver not in nameservers:
            nameservers.append(nameserver)
    return nameservers


def read_kernel_dhcp_resolver_config(path: Path | None = None) -> ResolverConfig:
    pnp_path = path or Path(KERNEL_DHCP_PNP_PATH)
    try:
        lines = pnp_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        lines = []

    nameservers: list[str] = []
    search_domains: list[str] = []

    for raw_line in lines:
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        key, _, value = line.partition(" ")
        value = value.strip()
        if not value:
            continue
        if key == "nameserver" and value not in nameservers:
            nameservers.append(value)
        if key == "domain":
            domain = _normalize_domain(value)
            if domain and domain not in search_domains:
                search_domains.append(domain)

    if not nameservers:
        # boot-media's recovery initramfs runs udhcpc before switching to NFS.
        # Its /run tmpfs survives switch_root; it does not populate /proc/net/pnp.
        fallback = pnp_path.absolute().parents[2] / "run/ha-pxe-initramfs/resolv.conf"
        nameservers = read_resolv_nameservers(fallback)
        if nameservers:
            search_domains = read_resolv_search_domains(fallback)
    return ResolverConfig(nameservers=nameservers, search_domains=search_domains)


def render_resolv_conf(config: ResolverConfig) -> str:
    lines = ["# Generated by HA-PXE from kernel DHCP boot data"]
    if config.search_domains:
        lines.append("search " + " ".join(config.search_domains))
    lines.extend(f"nameserver {nameserver}" for nameserver in config.nameservers)
    return "\n".join(lines) + "\n"


def is_loopback_nameserver(value: str) -> bool:
    candidate = value.strip().strip("[]")
    if "%" in candidate:
        candidate = candidate.split("%", 1)[0]
    try:
        return ipaddress.ip_address(candidate).is_loopback
    except ValueError:
        return candidate.lower() == "localhost"


def _normalize_domain(value: str) -> str:
    return value.strip().rstrip(".")
